#!/bin/bash -e

install -D -m 644 files/output.conf "${ROOTFS_DIR}/etc/alsa/conf.d/output.conf"

# ADR-0085: the ALSA default is our output, for software that enumerates its
# own device list and cannot be told about `pcm.output` - Plexamp is the case
# that found it. Its own file, because output.conf is regenerated by
# `outputs.render()` on every output change and this stanza never varies.
# `zz-` so it is read after output.conf defines what it points at.
install -D -m 644 files/zz-gexis-default.conf \
	"${ROOTFS_DIR}/etc/alsa/conf.d/zz-gexis-default.conf"

# B2, George's decision 2026-09-08: private snd-dummy mixer controls for
# LMS and Bluetooth (volume.py's DummyMixerBridge). Loaded at boot, not
# on demand - squeezelite.service and bluealsa-aplay's override both
# reference these cards by id unconditionally at their own startup.
install -D -m 644 files/gexis-dummy-mixers-load.conf \
	"${ROOTFS_DIR}/etc/modules-load.d/gexis-dummy-mixers.conf"
install -D -m 644 files/gexis-dummy-mixers-modprobe.conf \
	"${ROOTFS_DIR}/etc/modprobe.d/gexis-dummy-mixers.conf"
